<?php
session_start();
require_once "db.php";

if (!isset($_SESSION["user_id"])) {
    header("Location: login.php");
    exit();
}

$lesson_id = isset($_GET["lesson_id"]) ? (int)$_GET["lesson_id"] : 0;

if ($lesson_id <= 0) {
    die("Invalid lesson requested.");
}

$stmt = $conn->prepare(
    "SELECT l.title, l.lesson_number, l.document_title, l.document_content, c.title AS course_title, c.instructor
     FROM lessons l
     INNER JOIN courses c ON l.course_id = c.course_id
     WHERE l.lesson_id = ?
     LIMIT 1"
);
$stmt->bind_param("i", $lesson_id);
$stmt->execute();
$lesson = $stmt->get_result()->fetch_assoc();
$stmt->close();

if (!$lesson) {
    die("Lesson notes not found.");
}

$filename = preg_replace('/[^a-zA-Z0-9_-]/', '_', $lesson["title"]) . "_Notes.txt";

header('Content-Type: text/plain; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');

echo "=========================================================\n";
echo "LEARNORA AI CLASSROOM STUDY MATERIAL\n";
echo "Course: " . $lesson["course_title"] . "\n";
echo "Instructor: " . ($lesson["instructor"] ?? "Learnora AI") . "\n";
echo "Lesson #" . $lesson["lesson_number"] . ": " . $lesson["title"] . "\n";
echo "=========================================================\n\n";

if (!empty($lesson["document_title"])) {
    echo "DOCUMENT TITLE: " . $lesson["document_title"] . "\n";
    echo "---------------------------------------------------------\n\n";
}

if (!empty($lesson["document_content"])) {
    // Strip markdown formatting for plain text output
    $clean_content = str_replace(["### ", "## ", "# ", "**", "`"], "", $lesson["document_content"]);
    echo $clean_content . "\n\n";
} else {
    echo "No specific document text provided for this lesson.\n";
}

echo "\n---------------------------------------------------------\n";
echo "Generated by Learnora AI Learning Management Platform\n";
exit();
